### ISSUE TITLE
Mais iteratividade nos componentes

### ISSUE THREAD

**Issue by thayannevls** [lucasaires/devWeb#2]
Olá 👋 

Muito bom o projeto! Minha sugestão seria trazer mais iteratividade e ações que o usuário possa fazer na tela principal. Por exemplo a opção de ordenar os problemas por diferentes critérios(ex.: Por curtidas, por tempo de criação). Outra ideia seria uma caixa de pesquisa.

**Comment by lucasaires** [comment]
Anotado, será implementado.
