### ISSUE TITLE
Adicionar outro elemento para diferenciar além de cor.

### ISSUE THREAD

**Issue by thayannevls** [lucasaires/devWeb#3]
Essa issue é apenas uma dica, não se sinta na obrigação de adotar o que estou dizendo porque é bem opcional.

No frontend, diferenciar coisas por cores é um tema bem polêmico por conta de acessibilidade. Minha sugestãos seria além das cores, usar outro efeito visual para diferenciar os momentos dos problemas, por exemplo ícones.

**Comment by lucasaires** [comment]
Boa sugestão, acrescentarei ao Readme.
